from __future__ import annotations

from typing import Protocol

from src.domain.models.conversation import Conversation


class PersistencePort(Protocol):
    async def save_conversation(self, conversation: Conversation) -> None: ...
    async def load_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def list_conversations(self, user_id: str) -> list[Conversation]: ...
    async def delete_conversation(self, conversation_id: str) -> bool: ...
    async def save_graph_state(self, conversation_id: str, state: dict) -> None: ...
    async def load_graph_state(self, conversation_id: str) -> dict | None: ...
